### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by sibelius**
Only [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin) was not updated, breaking change

### CODE REVIEW

**Comment by tisto** [comment]
@sibelius thanks for the update! Though, the travis build fails and I would prefer to keep the package.json order. The "scripts" section is what people will look up most of the time, therefore I put it at the top of the file.

**Comment by sibelius** [comment]
@tisto. For the same reason I put the scripts section on the bottom, so devs can do a `cat package.json` in the command line and check what scripts ate available

**Comment by sibelius** [comment]
Tests are working fine, what is broken is the eslint config. Feel free to fix it

**Comment by tisto** [comment]
@sibelius ok, putting scripts to the bottom actually makes a lot of sense if you put it that way...

**Pull request closed without merging**
